name: Test on Browserstack

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  full:
    name: Full Build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: softprops/turnstyle@v1
      with:
        poll-interval-seconds: 30
        abort-after-seconds: 900
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-node@v2
    - run: npm ci
    - run: npm run build-test
    - run: npm run browserstack

  lightweight:
    name: Lightweight Build

    needs: full

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: softprops/turnstyle@v1
      with:
        poll-interval-seconds: 30
        abort-after-seconds: 900
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-node@v2
    - run: npm ci
    - run: npm run build-test --lightweight
    - run: npm run browserstack
      env:
        LIGHTWEIGHT: true

env:
  BROWSERSTACK_USERNAME: danielhuigens2
  BROWSERSTACK_KEY: aW2q1ms393QRorwBnfmW
